// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqbhhfpfnsgoxtizaycw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxYmhoZnBmbnNnb3h0aXpheWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjIzMDEsImV4cCI6MjA2ODE5ODMwMX0.W-DtLLLa7WayhJkSLEM6lN18eEYqoTtS5wgzLyN9i14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});